### ISSUE TITLE
Failed in Citavi 6.8

### ISSUE THREAD

**Issue by AngelontheRoad** [lutz/JumpToLastPositionAfterActionExecutionAddon#4]
SessionId: f656f2ca-410d-4947-9e9b-1bf01b7c20ae
System.NullReferenceException: Object reference not set to an instance of an object.
   at JumpToLastPositionAfterActionExecution.Addon.MainForm_FormClosed(Object sender, FormClosedEventArgs e)
   at System.Windows.Forms.Form.OnFormClosed(FormClosedEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at SwissAcademic.Controls.FormBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by lutz** [comment]
@AngelontheRoad 

Hi,
i am on parental leave until mid-February. After that I'll take a look. Citavi 6.8 brings an updated PDF component. This problem should be easy to fix if i have the time to look into.

**Comment by AngelontheRoad** [comment]
Thanks for your reply! I'm appreciated to see new features in Citavi 6.8 if they work properly. And I've banned the Add-on to avoid this problem.

**Comment by lutz** [comment]
With this [version](https://github.com/lutz/JumpToLastPositionAfterActionExecutionAddon/releases/tag/v1.0.2) the addon should works again with Citavi 6.8
